#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019-2024
# Copyright (c) Toshiba Corporation, 2020
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#  Quirin Gylstorff <quirin.gylstorff@siemens.com>
#  Nobuhiro Iwamatsu <nobuhiro1.iwamatsu@toshiba.co.jp>
#
# SPDX-License-Identifier: MIT
#

image: ghcr.io/siemens/kas/kas-isar:4.7

variables:
  GIT_STRATEGY: clone
  release: bookworm
  extension: none
  use_rt: enable
  encrypt: disable
  targz: enable
  dtb: none
  deploy: enable
  deploy_kernelci: disable
  build_swu_v2: disable
  swupdate_version: default
  test_function: swupdate
  separate_home_partition: disable

stages:
  - build
  - test
  - cve-check

default:
  before_script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export DISTRO_APT_PREMIRRORS=$DISTRO_APT_PREMIRRORS

.build_base:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH != "master"
  tags:
    - large
  variables:
    base_yaml: "kas-cip.yml:kas/board/${target}.yml"
  script:
    - if [ "${use_rt}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/rt.yml"; fi
    - if [ "${extension}" != "none" ]; then base_yaml="${base_yaml}:kas/opt/${extension}.yml"; fi
    - if [ "${targz}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/targz.yml"; fi
    - if [ "${separate_home_partition}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/separate-home-partition.yml"; fi
    - if [ "${release}" = "buster" ]; then base_yaml="${base_yaml}:kas/opt/buster.yml"; fi
    - if [ "${release}" = "bullseye" ]; then base_yaml="${base_yaml}:kas/opt/bullseye.yml"; fi
    - if [ "${release}" = "bookworm" ]; then base_yaml="${base_yaml}:kas/opt/bookworm.yml"; fi
    - if [ "${release}" = "trixie" ]; then base_yaml="${base_yaml}:kas/opt/trixie.yml"; fi
    - if [ "${encrypt}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/encrypt-data.yml"; fi
    - if [ "${watchdog}" = "disable" ]; then base_yaml="${base_yaml}:kas/opt/disable-watchdog.yml"; fi
    - if [ "${security_test}" = "enable" ]; then base_yaml="${base_yaml}:kas/opt/security_test.yml"; fi
    - if [ "${swupdate_version}" = "2022.12" ]; then base_yaml="${base_yaml}:kas/opt/swupdate-2022.12.yaml"; fi
    - echo "Building ${base_yaml}"
    - kas build ${base_yaml}
    - if [ "${deploy}" = "enable" ]; then scripts/deploy-cip-core.sh ${release} ${target} ${extension} ${dtb} ${CI_COMMIT_REF_SLUG} wic; fi
    - if [ "${build_swu_v2}" = "enable" ]; then
          mkdir build/previous-image;
          if [ "${extension}" = "security" ] || [ "${extension}" = "ebg-secure-boot-snakeoil" ]; then
              cp build/tmp/deploy/images/${target}/*.verity build/previous-image;
          else
              cp build/tmp/deploy/images/${target}/*.squashfs build/previous-image;
          fi;
          base_yaml="${base_yaml}:kas/opt/kernel-panic.yml";
          kas build ${base_yaml}:kas/opt/delta-update.yml;
          scripts/deploy-cip-core.sh ${release} ${target} ${extension} ${dtb} ${CI_COMMIT_REF_SLUG} swu;
      fi
    - if [ "${deploy_kernelci}" = "enable" ]; then scripts/deploy-kernelci.py ${release} ${target} ${extension} ${dtb}; fi

# base image
build:qemu-amd64-base:
  extends:
    - .build_base
  variables:
    target: qemu-amd64
    extension: security
    security_test: enable
    use_rt: disable
    build_swu_v2: enable
    separate_home_partition: enable

.test-cip-core:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH != "master"
  tags:
    - small
  script:
    - scripts/submit_lava.sh ${test_function} ${target} ${CI_COMMIT_SHORT_SHA} ${release} ${CI_COMMIT_REF_SLUG} ${iec_test_timeout}
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    expire_in: 1 day
    paths:
      - results
    reports:
      junit: results/results*.xml

test:qemu-amd64-swupdate-kernel-panic:
  extends:
    - .test-cip-core
  needs: ["build:qemu-amd64-base"]
  variables:
    target: qemu-amd64
    test_function: kernel-panic

include: '.reproducible-check-ci.yml'
