#
# CIP Core, generic profile
#
# Copyright (c) Toshiba Corporation, 2023
#
# Authors:
#  Venkata Pyla <venkata.pyla@toshiba-tsip.com>
#
# SPDX-License-Identifier: MIT
#
# extension to gitlab-ci for reproducible checks

.repro-build:
  variables:
    use_rt: disable
    wic_targz: disable
    targz: enable
    deploy: disable
    deploy_kernelci: disable
    artifact_suffix: ".tar.gz"
    base_yaml: "kas-cip.yml:kas/board/${target}.yml"
  stage: build
  tags:
    - large
  only:
    - schedules
  script:
    - if [ -f kas/opt/reproducible.yml ]; then base_yaml="${base_yaml}:kas/opt/reproducible.yml"; fi
    # Build 1st time
    - !reference [.build_base, script]
    - mv build/tmp/deploy/images/${target} image1
    # clean
    - sudo rm -rf build/tmp
    - sudo rm -rf build/sstate-cache
    # Build 2nd time
    - !reference [.build_base, script]
    - mv build/tmp/deploy/images/${target} image2
  artifacts:
    expire_in: 1 day
    paths:
      - scripts/repro-tests.sh
      - image*/*initrd.img
      - image*/*-vmlinu*
      - image*/*.tar.gz
      - image*/*.squashfs
      - image*/*.swu
      - image*/linux.efi

.repro-test:
  image:
    name: debian:bullseye
  tags:
    - large
  stage: test
  only:
    - schedules
  variables:
    GIT_STRATEGY: none
  before_script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y diffoscope
  script:
    - ./scripts/repro-tests.sh --release ${release} --target ${target} image1 image2
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - "./*diffoscope_output.txt"


# repro build
build:qemu-amd64-repro-build:
  extends:
    - .repro-build
  variables:
    target: qemu-amd64
    extension: ebg-swu
    wic_targz: enable

build:qemu-arm64-repro-build:
  extends:
    - .repro-build
  variables:
    target: qemu-arm64
    extension: ebg-swu
    wic_targz: enable

build:qemu-arm-repro-build:
  extends:
    - .repro-build
  variables:
    target: qemu-arm
    extension: ebg-swu
    wic_targz: enable

# repro build test
test:qemu-amd64-repro-test:
  extends:
    - .repro-test
  variables:
    target: qemu-amd64
  dependencies:
    - build:qemu-amd64-repro-build

test:qemu-arm64-repro-test:
  extends:
    - .repro-test
  variables:
    target: qemu-arm64
  dependencies:
    - build:qemu-arm64-repro-build

test:qemu-arm-repro-test:
  extends:
    - .repro-test
  variables:
    target: qemu-arm
  dependencies:
    - build:qemu-arm-repro-build
