#
# CIP Core, generic profile
#
# Copyright (c) Toshiba Corporation, 2023
#
# Authors:
#  Venkata Pyla <venkata.pyla@toshiba-tsip.com>
#
# SPDX-License-Identifier: MIT
#
# extension to gitlab-ci for reproducible checks

.repro-build:
  variables:
    use_rt: disable
    deploy: disable
    base_yaml: "kas-cip.yml:kas/board/${target}.yml:kas/opt/reproducible.yml"
    release: bookworm
    # This target include base + swupdate + secureboot + security
    extension: security
  stage: build
  tags:
    - large
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $REPRODUCIBLE_BUILDS
  script:
    # Build 1st time
    - !reference [.build_base, script]
    - mv build/tmp/deploy/images/${target} image1
    # clean
    - sudo rm -rf build/tmp
    - sudo rm -rf build/sstate-cache
    # Build 2nd time
    - !reference [.build_base, script]
    - mv build/tmp/deploy/images/${target} image2
    # Compress artifacts
    - tar --ignore-failed-read -cJf image1.tar.xz image1/*.wic* image1/*.swu
    - tar --ignore-failed-read -cJf image2.tar.xz image2/*.wic* image2/*.swu
  artifacts:
    expire_in: 1 day
    paths:
      - scripts/repro-tests.sh
      - image*.tar.xz

.repro-test:
  image:
    name: debian:bullseye
  tags:
    - large
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $REPRODUCIBLE_BUILDS
  variables:
    GIT_STRATEGY: none
    release: bookworm
    extension: security
  before_script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y diffoscope
  script:
    - mkdir image1
    - tar -xJf image1.tar.xz --strip-components=1 -C image1
    - mkdir image2
    - tar -xJf image2.tar.xz --strip-components=1 -C image2
    - ./scripts/repro-tests.sh --release ${release} --target ${target} --extension ${extension} image1 image2
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - "diffoscope_output"
      - "./*diffoscope_output.*"


# repro build
build:qemu-amd64-repro-build:
  extends:
    - .repro-build
  variables:
    target: qemu-amd64

build:qemu-arm64-repro-build:
  extends:
    - .repro-build
  variables:
    target: qemu-arm64

build:qemu-arm-repro-build:
  extends:
    - .repro-build
  variables:
    target: qemu-arm

build:bbb-repro-build:
  extends:
    - .repro-build
  variables:
    target: bbb
    extension: "none"

# repro build test
test:qemu-amd64-repro-test:
  extends:
    - .repro-test
  variables:
    target: qemu-amd64
  dependencies:
    - build:qemu-amd64-repro-build

test:qemu-arm64-repro-test:
  extends:
    - .repro-test
  variables:
    target: qemu-arm64
  dependencies:
    - build:qemu-arm64-repro-build

test:qemu-arm-repro-test:
  extends:
    - .repro-test
  variables:
    target: qemu-arm
  dependencies:
    - build:qemu-arm-repro-build

test:bbb-repro-test:
  extends:
    - .repro-test
  variables:
    target: bbb
    extension: "none"
  dependencies:
    - build:bbb-repro-build
