#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019
# Copyright (c) Cybertrust Japan Co., Ltd., 2021
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#  Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
#
# SPDX-License-Identifier: MIT
#

echo "CIP Core Demo & Test Image" > /etc/issue

# permit root login without password
passwd root -d

# set the profile for KernelCI
echo "PS1='\$(pwd) # '" > /root/.profile
echo "cd /" >> /root/.profile

