#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2025
#
# Authors:
#  Quirin Gylstorff <quirin.gylstorff@siemens.com>
#
# SPDX-License-Identifier: MIT
#

set -e

if [ ! -L /home ]; then
	# usermod --move-home can not be used while the target user
	# has running processes, also we keep a symlink here
	mv /home /var/
	ln -s /var/home /home
fi
