#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# SPDX-License-Identifier: MIT
#

set -e

echo "CIP Core Demo & Test Image (login: root/root)" > /etc/issue

if ! grep -e "^PermitRootLogin.*yes" -q /etc/ssh/sshd_config; then
	echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
fi

HOSTNAME=demo
echo "$HOSTNAME" > /etc/hostname
echo "127.0.0.1 $HOSTNAME" >> /etc/hosts
