#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019-2023
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# SPDX-License-Identifier: MIT
#

set -e

# needed for read-only rootfs with writable /home
if [ ! -L /root ]; then
	# usermod --move-home can not be used while the target user
	# has running processes, also we keep a symlink here
	mv /root /home/
	ln -s /home/root /root
fi
